name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: expression-machine/tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: expression-machine

      - name: Pull `unmanaged` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged

      - name: Pull `collections` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: List directory
        run: ls

      - name: Test project
        run: dotnet test -c Debug --collect:"XPlat Code Coverage" --results-directory:"TestResults"
